[Rainmeter]
Update=1000
@include=#@#themes\current.inc

[Metadata]
Name=1-Line Clock
Author=Jeffrey Earl (based on Feedanza)
Information=Date and time in a compact layout

[StyleDate]
FontColor=#clock.color#
FontSize=10
FontFace=#FontName#
StringStyle=Normal
StringAlign=Left
StringCase=Upper
AntiAlias=1

[StyleTime]
FontColor=#clock.color#
FontSize=24
FontFace=#FontName#
StringStyle=Normal
StringAlign=Right
StringCase=Upper
AntiAlias=1

;------------------------------------------------------------
; DATE
;------------------------------------------------------------

[mDay]
Measure=Time
Format=%d

[mWeekday]
Measure=Time
Format=%a

[mMonth]
Measure=Time
Format=%b

[sDay]
Meter=STRING
MeterStyle=StyleTime
MeasureName=mDay
X=50
Y=0

[sMonth]
Meter=STRING
MeterStyle=StyleDate
MeasureName=mMonth
X=60
Y=6

[sWeekday]
Meter=STRING
MeterStyle=StyleDate
MeasureName=mWeekday
X=60
Y=21

;------------------------------------------------------------
; TIME
;------------------------------------------------------------

[mTime]
Measure=Time
Format=%H:%M

[mIndicator]
Measure=Time
Format=%p

[sTime]
Meter=STRING
MeterStyle=StyleTime
MeasureName=mTime
X=200
Y=0

[sIndicator]
Meter=STRING
MeterStyle=StyleDate
MeasureName=mIndicator
X=210
Y=6
